---
# TP LABO - Fenómeno de El Niño
---

Poner algo que diga de qué va el colab, despues se completa, son detalles

# 🔍 3.1 Exploración inicial de los Datasets

### Dataset "smn_estaciones_meteorologicas21-26.xlsx":

In [59]:
#Importamos las librerías que vamos a utilizar
import pandas as pd #para manejo de archivos de datos
import numpy as np #para realizar cálculos numéricos y matemáticos
import matplotlib.pyplot as plt #para graficar

In [60]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_estaciones_meteorologicas21-26.xlsx

In [61]:
#Cargamos los datos
estaciones = pd.read_excel(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # read_excel: leer una planilla de Excel

In [62]:
# Leemos las primeras 5 lineas del principio:
estaciones.head()

   NRO_OMM             NOMBRE     PROVINCIA   LATITUD  LONGITUD  ALTURA
0    87544       PEHUAJO AERO  BUENOS AIRES -35.84070 -61.85978      87
1    87548         JUNIN AERO  BUENOS AIRES -34.55251 -60.93127      81
2    87550     NUEVE DE JULIO  BUENOS AIRES -35.43899 -60.88191      76
3    87553  SAN FERNANDO AERO  BUENOS AIRES -34.45502 -58.58449       5
4    87563         LAS FLORES  BUENOS AIRES -36.04149 -59.13724      36

In [63]:
# Leemos las últimas 5 lineas del dataset:
estaciones.tail()

,NRO_OMM,NOMBRE,PROVINCIA,LATITUD,LONGITUD,ALTURA
87,87470,EL TRÉBOL,SANTA FE,-32.19216,-61.71198,96
88,87129,SANTIAGO DEL ESTERO AERO,SANTIAGO DEL ESTERO,-27.75481,-64.29980,199
89,87934,RÍO GRANDE B.A.,TIERRA DEL FUEGO,-53.78026,-67.75871,22
90,87938,USHUAIA AERO,TIERRA DEL FUEGO,-54.84005,-68.30342,57
91,87121,TUCUMÁN AERO,TUCUMÁN,-26.83730,-65.10843,450

In [64]:
#Describimos la estructura del Dataset:
#--------------------------------------

#Tipo de datos definidos:
print('Tipo de datos:')
print(estaciones.dtypes)
print('')
print('-'*50)

#Veamos sus dimensiones:
print("Dimensiones:", estaciones.shape, "  ← (Filas, Columnas)")
print('-'*50)
print('')

#Veamos la calidad de datos: hay varios puntos
print('Tiene nulos? No! No tiene Nulos!')
print(estaciones.info())
print('')
print('Pero por las dudas verifico los nulos por columna:')
print(estaciones.isnull().sum())
print('')
print('Confirmado, no hay valores nulos ya que dieron todas cero.')
print('-'*50)
print('')

print('Revisamos si hay duplicados:')
print("Filas duplicadas:", estaciones.duplicated().sum())
if estaciones.duplicated().sum() == 0:
  print('No hay duplicados!')
else:
  print('Hay filas duplicadas, vamos a revisar un poco más y eliminarlas')
print('-'*50)
print('')

print('Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad')
display(estaciones.describe().T)

Tipo de datos:
NRO_OMM        int64
NOMBRE        object
PROVINCIA     object
LATITUD      float64
LONGITUD     float64
ALTURA         int64
dtype: object

--------------------------------------------------
Dimensiones: (92, 6)   ← (Filas, Columnas)
--------------------------------------------------

Tiene nulos? No! No tiene Nulos!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NRO_OMM    92 non-null     int64
 1   NOMBRE     92 non-null     object
 2   PROVINCIA  92 non-null     object
 3   LATITUD    92 non-null     float64
 4   LONGITUD   92 non-null     float64
 5   ALTURA     92 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 4.4+ KB
None

Pero por las dudas verifico los nulos por columna:
NRO_OMM      0
NOMBRE       0
PROVINCIA    0
LATITUD      0
LONGITUD     0
ALTURA       0
dtype: int64

Confirmado, no hay valores nulos ya que dieron todas cero.
--------------------------------------------------

Revisamos si hay duplicados:
Filas duplicadas: 0
No hay duplicados!
--------------------------------------------------

Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad

,count,mean,std,min,25%,50%,75%,max
NRO_OMM,92.0,87475.369565,256.950404,87007.00000,87266.750000,87488.50000,87645.750000,87938.00000
LATITUD,92.0,-34.387620,7.009355,-54.84005,-37.294213,-33.70020,-29.828997,-22.10343
LONGITUD,92.0,-63.227429,4.398605,-72.05149,-66.461883,-63.54759,-59.578342,-53.67121
ALTURA,92.0,341.423913,476.374177,5.00000,53.750000,146.00000,451.000000,3459.00000

## Dataset "smn_datos_meteorologicos_1991_2020.xlxs":

In [65]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_datos_meteorologicos_1991_2020.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_datos_meteorologicos_1991_2020.xlsx

In [66]:
#Cargamos los datos del dataset período 1991-2020
smn_1991_2020 = pd.read_excel(URL + "smn_datos_meteorologicos_1991_2020.xlsx")   # read_excel: leemos el archivo excel

A continuación comenzamos a trabajar con el Datase propiamente dicho. Vamos a describir su estructura.

A) Buscamos ver cuántos registros contiene el archivo y cuántas variables se encuentran disponibles. Nos va permitir tener una idea del tamaño del conjunto de datos con el que vamos a trabajar.

B) Revisamos el nombre de las columnas lo que nos permite saber qué variables meteorológicas contiene. También ver otras posibles columnas como ser nombre de la estación, fecha de medición, etc.

C) Examinamos los tipos de datos. Vemos cómo Python está intepretando la información del set de datos. Por ejemplo, ¿las fechas están como texto? ¿valores numéricos están como tales?

D) Analizamos si hay valores faltantes en el Dataset.

E) Verificamos si existen registros que contienen exactamente la misma información en todas sus columnas (duplicaciones).

F) Un poco de Estadística Descriptiva de los datos.

In [67]:
# Leemos las primeras 5 filas para comenzar a tener una idea de este set de datos:
smn_1991_2020.head()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL
0,87007,LA QUIACA OBSERVATORIO,1991-01-01,18.4,5.4,13.3,5.2,S/D,5,9,6,671.4,64,7
1,87007,LA QUIACA OBSERVATORIO,1991-01-02,18.2,8.4,12.3,8,S/D,32,15,8,670.7,73,7
2,87007,LA QUIACA OBSERVATORIO,1991-01-03,19.4,6,13.7,NaN,S/D,5,9,4,672,61,4
3,87007,LA QUIACA OBSERVATORIO,1991-01-04,19.3,4.9,13.1,NaN,S/D,7,15,2,673.2,55,4
4,87007,LA QUIACA OBSERVATORIO,1991-01-05,21,6,14.2,NaN,S/D,5,15,6,673.4,60,4

In [68]:
# Leemos las últimas 5 filas del dataset:
smn_1991_2020.tail()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL
992179,87938,USHUAIA AERO,2020-12-27,22.2,7.2,13.6,0.0,8.7,29,93,16,992.7,58,5
992180,87938,USHUAIA AERO,2020-12-28,17.5,7.3,9.7,2.0,4.6,23,44,16,1002.4,75,7
992181,87938,USHUAIA AERO,2020-12-29,13.5,6.0,9.5,0.0,10.6,23,57,18,995.6,71,7
992182,87938,USHUAIA AERO,2020-12-30,12.8,5.4,8.8,NaN,0.9,23,54,15,991.7,66,6
992183,87938,USHUAIA AERO,2020-12-31,15.5,9.6,11.8,0.0,10.0,23,57,28,988.7,66,5

In [69]:
#Describimos la estructura del Dataset:
#------------------------------------------------------

#1 - Dimensiones del Conjunto de Datos

# Consultamos las dimensiones del conjunto de datos.
# shape devuelve la cantidad de filas y columnas.

print(f"Dimensiones: {smn_1991_2020.shape}")

# Mostramos por separado la cantidad de registros y variables.
print(f"\nCantidad de filas: {smn_1991_2020.shape[0]}")
print(f"\nCantidad de columnas: {smn_1991_2020.shape[1]}")
print('')


#2 - Tipos de datos

# Consultamos el tipo de dato de cada columna.
# Esto permite distinguir variables numéricas, textos y fechas.

print(smn_1991_2020.dtypes)
print('')


# Obtenemos información general de la tabla: tipo de dato y cantidad de valores no nulos de cada columna.

print(smn_1991_2020.info())
print('')

#Examinando la calidad de los datos del Dataset:
#------------------------------------------------------

#3 - Valores faltantes

# Contamos los valores faltantes en cada columna.

print(smn_1991_2020.isnull().sum())
print('')

#4 - Valores duplicados

# Contamos cuántas filas están completamente duplicadas.

print(f"\nFilas duplicadas: {smn_1991_2020.duplicated().sum()}")
print('')


#Un poco de Estadística Descriptiva de los datos del Dataset:
#------------------------------------------------------

#print('Veamos información estadísticas descrptiva básica:')
#display(smn_1991_2020.describe().T)

Dimensiones: (992184, 14)

Cantidad de filas: 992184

Cantidad de columnas: 14

NRO_OMM               int64
NOMBRE               object
FECHA        datetime64[ns]
TMAX                 object
TMIN                 object
TMEDIA               object
PRECIP               object
HELIOF               object
VTO_MDIR             object
VTO_MVEL             object
VEL_MED              object
PRE_EST              object
HUM_REL              object
NUB_TOTAL            object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992184 entries, 0 to 992183
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   NRO_OMM    992184 non-null  int64
 1   NOMBRE     992184 non-null  object
 2   FECHA      992184 non-null  datetime64[ns]
 3   TMAX       992184 non-null  object
 4   TMIN       992184 non-null  object
 5   TMEDIA     992184 non-null  object
 6   PRECIP     274605 non-null  object
 7   HELIOF     992184 non-null  object
 8   VTO_MDIR   992184 non-null  object
 9   VTO_MVEL   992184 non-null  object
 10  VEL_MED    992184 non-null  object
 11  PRE_EST    992184 non-null  object
 12  HUM_REL    992184 non-null  object
 13  NUB_TOTAL  992184 non-null  object
dtypes: datetime64[ns](1), int64(1), object(12)
memory usage: 106.0+ MB
None

NRO_OMM           0
NOMBRE            0
FECHA             0
TMAX              0
TMIN              0
TMEDIA            0
PRECIP       717579
HELIOF            0
VTO_MDIR          0
VTO_MVEL          0
VEL_MED           0
PRE_EST           0
HUM_REL           0
NUB_TOTAL         0
dtype: int64


Filas duplicadas: 0

Algunas cuestiones que detectamos en este primer análisis:

TMAX                 object
TMIN                 object
TMEDIA               object
PRECIP               object
HELIOF               object
VTO_MDIR             object
VTO_MVEL             object
VEL_MED              object
PRE_EST              object
HUM_REL              object
NUB_TOTAL            object

11 variables meteorológicas aparecen como object. Varias de ellas deberían ser numéricas como por Precitipación, TMAX, TMIN.

Precipitación presenta 717579 valores nulos de un total de 992184. El 72,32%

Se trabajo con IA para analizar cuántos valores de cada variable meteorológica no pueden convertirse directamente en números. Esto nos permitirá decidir cómo preparar las columnas para calcular estadísticas descriptivas.

PROMPT: Hemos obtenido los siguentes resultados al analizar el tipo de datos. Variables que deberían ser numéricas aparecen como texto. Antes de comenzar a trabajar con los ajustes que pudieran ser necesarios, ¿podemos pensar un código para ver si los datos igualmente podrían ser trabajados con Pandas?

In [70]:
# Seleccionamos las columnas que contienen variables meteorológicas.
# Excluimos los identificadores de estación y la fecha.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Revisamos los valores que no pueden interpretarse como números.
# errors="coerce" convierte temporalmente esos valores en NaN.
# No modificamos los datos originales.

for columna in variables_meteo:
    valores = pd.to_numeric(smn_1991_2020[columna], errors="coerce")

    # Contamos los valores no nulos originales que no son numéricos.
    no_numericos = (
        valores.isna() & smn_1991_2020[columna].notna()
    ).sum()

    print(columna, ":", no_numericos, "valores no numéricos")

TMAX : 20993 valores no numéricos
TMIN : 24425 valores no numéricos
TMEDIA : 8551 valores no numéricos
PRECIP : 2244 valores no numéricos
HELIOF : 126035 valores no numéricos
VTO_MDIR : 14836 valores no numéricos
VTO_MVEL : 14831 valores no numéricos
VEL_MED : 10455 valores no numéricos
PRE_EST : 26755 valores no numéricos
HUM_REL : 9845 valores no numéricos
NUB_TOTAL : 9264 valores no numéricos

Confirmamos que todas las variables meteorológicas tienen algunos valores que pandas no puede interpretar directamente como números.

A partir de estos resultados, y teniendo en cuenta que una columna aparezca como object no significa que todos sus valores sean no numéricos (algo de esto ya lo podemos intuir de ver los valores no númericos y el resultado del análisis del tipo de datos), analizamos valores numéricos, no numéricos y nulos para estas variables meteorológicas.

Se trabaja con IA para la formulación del código que nos permita ver esto último. PROMPT: Vamos a armar un código para contar los valores numéricos, no numéricos y nulos de todas las variables meteorológicas del DataFrame smn_1991_2020, teniendo en cuenta no modificar los datos originales.

In [71]:
# Seleccionamos las columnas meteorológicas.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Recorremos las variables para conocer cuántos registros son convertibles a números, no convertibles o nulos.

for columna in variables_meteo:

    convertida = pd.to_numeric(
        smn_1991_2020[columna],
        errors="coerce"
    )

    numericos = convertida.notna().sum()

    no_numericos = (
        convertida.isna() & smn_1991_2020[columna].notna()
    ).sum()

    nulos = smn_1991_2020[columna].isna().sum()

    print(
        columna,
        "| Numéricos:", numericos,
        "| No numéricos:", no_numericos,
        "| Nulos:", nulos
    )

TMAX | Numéricos: 971191 | No numéricos: 20993 | Nulos: 0
TMIN | Numéricos: 967759 | No numéricos: 24425 | Nulos: 0
TMEDIA | Numéricos: 983633 | No numéricos: 8551 | Nulos: 0
PRECIP | Numéricos: 272361 | No numéricos: 2244 | Nulos: 717579
HELIOF | Numéricos: 866149 | No numéricos: 126035 | Nulos: 0
VTO_MDIR | Numéricos: 977348 | No numéricos: 14836 | Nulos: 0
VTO_MVEL | Numéricos: 977353 | No numéricos: 14831 | Nulos: 0
VEL_MED | Numéricos: 981729 | No numéricos: 10455 | Nulos: 0
PRE_EST | Numéricos: 965429 | No numéricos: 26755 | Nulos: 0
HUM_REL | Numéricos: 982339 | No numéricos: 9845 | Nulos: 0
NUB_TOTAL | Numéricos: 982920 | No numéricos: 9264 | Nulos: 0

A partir de los resultados, vamos a evaluar qué valores no numéricos aparecen en nuestro set de datos. Por ejemplo: S/D, un guión, un espacio.

PROMPT: Escribir un código que nos permita identificar exactamente qué valores no numéricos aparecen en cada variable meteorológica y cuántas veces se repiten.

In [72]:
# Seleccionamos las variables meteorológicas.
# Excluimos el código de estación, el nombre y la fecha.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Recorremos cada variable meteorológica.

for columna in variables_meteo:

    # Intentamos convertir los valores a números.
    # Los que no pueden convertirse pasan temporalmente a NaN.

    convertida = pd.to_numeric(
        smn_1991_2020[columna],
        errors="coerce"
    )

    # Seleccionamos los valores que no pudieron convertirse,
    # excluyendo aquellos que ya eran nulos.

    no_numericos = smn_1991_2020.loc[
        convertida.isna() & smn_1991_2020[columna].notna(),
        columna
    ]

    # Mostramos los distintos valores no numéricos
    # y la cantidad de veces que aparece cada uno.

    print("\nVariable:", columna)
    print(no_numericos.value_counts(dropna=False))

Variable: TMAX
TMAX
S/D    20993
Name: count, dtype: int64

Variable: TMIN
TMIN
S/D    24425
Name: count, dtype: int64

Variable: TMEDIA
TMEDIA
S/D    8551
Name: count, dtype: int64

Variable: PRECIP
PRECIP
S/D    2244
Name: count, dtype: int64

Variable: HELIOF
HELIOF
S/D    126035
Name: count, dtype: int64

Variable: VTO_MDIR
VTO_MDIR
S/D    14836
Name: count, dtype: int64

Variable: VTO_MVEL
VTO_MVEL
S/D    14831
Name: count, dtype: int64

Variable: VEL_MED
VEL_MED
S/D    10455
Name: count, dtype: int64

Variable: PRE_EST
PRE_EST
S/D    26755
Name: count, dtype: int64

Variable: HUM_REL
HUM_REL
S/D    9845
Name: count, dtype: int64

Variable: NUB_TOTAL
NUB_TOTAL
S/D    9264
Name: count, dtype: int64

Este último resultado nos permitió confirmar que en las 11 variables meteorológicas el único valor no numérico identificado es S/D

# Dataset "indices_enso_noaa_pacifico.csv":

In [73]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "indices_enso_noaa_pacifico.csv")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/indices_enso_noaa_pacifico.csv

In [74]:
prueba = pd.read_csv(URL + "indices_enso_noaa_pacifico.csv")
prueba.head() # Muestro las 5 primeras filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
0,1950-01-01,1950,JAN,23.01,-1.55,23.56,-2.10,24.55,-1.99,26.94,...,-2.34,DJ,NaN,DJF,-1.32,-1.19,La Niña,Moderado,La Niña,Moderado
1,1950-02-01,1950,FEB,24.32,-1.78,24.89,-1.52,25.06,-1.69,26.67,...,-1.04,JF,NaN,JFM,-1.20,-1.08,La Niña,Moderado,La Niña,Moderado
2,1950-03-01,1950,MAR,25.11,-1.38,26.36,-0.84,25.87,-1.42,26.52,...,0.24,FM,NaN,FMA,-1.12,-0.96,La Niña,Moderado,La Niña,Moderado
3,1950-04-01,1950,APR,23.63,-1.90,26.44,-1.14,26.28,-1.54,26.90,...,0.01,MA,NaN,MAM,-1.08,-1.00,La Niña,Moderado,La Niña,Moderado
4,1950-05-01,1950,MAY,22.68,-1.74,25.69,-1.57,26.18,-1.75,27.73,...,-0.55,AM,NaN,AMJ,-1.10,-0.99,La Niña,Moderado,La Niña,Moderado

In [75]:
prueba.tail() # Muestro las 5 ultimas filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
916,2026-05-01,2026,MAY,26.23,1.82,28.41,1.16,28.83,0.90,30.00,...,-1.2693,AM,0.27,AMJ,0.95,0.49,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
917,2026-06-01,2026,JUN,25.94,2.82,28.33,1.71,29.17,1.44,30.19,...,-0.5005,MJ,1.52,MJJ,1.39,0.97,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
918,2026-07-01,2026,JUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6149,JJ,2.41,JJA,1.80,1.36,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
919,2026-08-01,2026,AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0797,JA,2.54,JAS,2.16,1.69,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
920,2026-09-01,2026,SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.6415,AS,2.37,ASO,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
print("Dimensiones", prueba.shape)
print("Filas:", prueba.shape[0], " Columnas:", prueba.shape[1])

Dimensiones (921, 26)
Filas: 921  Columnas: 26

In [77]:
prueba.info() # Me sirve para saber que tipo de objeto tiene cada columna, tambien veo los null como por ejemplo de la columna 18 "MEI.v2" tiene 573 no null(datos) y el resto estan vacios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  921 non-null    object
 1   Year                  921 non-null    int64
 2   Month                 921 non-null    object
 3   Nino 1+2 SST          918 non-null    float64
 4   Nino 1+2 SST Anomaly  918 non-null    float64
 5   Nino 3 SST            918 non-null    float64
 6   Nino 3 SST Anomaly    918 non-null    float64
 7   Nino 3.4 SST          918 non-null    float64
 8   Nino 3.4 SST Anomaly  918 non-null    float64
 9   Nino 4 SST            918 non-null    float64
 10  Nino 4 SST Anomaly    918 non-null    float64
 11  TNI                   917 non-null    float64
 12  SOI                   909 non-null    float64
 13  SOI estandarizado     909 non-null    float64
 14  OLR                   612 non-null    float64
 15  OLR anomalia          612 non-null    float64
 16  PNA                   921 non-null    float64
 17  Season (2-Month)      921 non-null    object
 18  MEI.v2                573 non-null    float64
 19  Season (3-Month)      921 non-null    object
 20  ONI                   920 non-null    float64
 21  RONI                  920 non-null    float64
 22  Fase ENSO (ONI)       920 non-null    object
 23  Intensidad (ONI)      479 non-null    object
 24  Fase ENSO (RONI)      920 non-null    object
 25  Intensidad (RONI)     480 non-null    object
dtypes: float64(17), int64(1), object(8)
memory usage: 187.2+ KB

In [78]:
prueba.describe() #Aca veo datos mas estadisticos como el min, max, percentiles, promedio etc

,Year,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,Nino 4 SST Anomaly,TNI,SOI,SOI estandarizado,OLR,OLR anomalia,PNA,MEI.v2,ONI,RONI
count,921.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,917.000000,909.000000,909.000000,612.000000,612.000000,921.000000,573.000000,920.000000,920.000000
mean,1987.876221,23.055741,-0.239412,25.790414,-0.202723,26.906362,-0.173878,28.406939,-0.241874,-0.266052,0.241914,0.147855,0.061275,0.976471,0.051977,-0.065654,0.020978,0.023337
std,22.168080,2.268865,1.104712,1.293583,0.903206,0.988674,0.871854,0.726662,0.690128,1.222150,1.557048,0.941042,0.973791,15.191442,0.997513,0.986425,0.790342,0.807785
min,1950.000000,18.920000,-3.090000,22.580000,-2.400000,24.250000,-2.450000,26.300000,-2.210000,-2.674000,-6.000000,-3.600000,-2.800000,-44.000000,-3.070000,-2.420000,-2.040000,-1.950000
25%,1969.000000,21.150000,-0.980000,24.790000,-0.820000,26.212500,-0.780000,27.920000,-0.720000,-1.168000,-0.700000,-0.400000,-0.600000,-9.125000,-0.660000,-0.770000,-0.510000,-0.500000
50%,1988.000000,22.810000,-0.410000,25.790000,-0.300000,26.975000,-0.250000,28.460000,-0.190000,-0.409000,0.300000,0.200000,0.200000,2.400000,0.120000,-0.150000,-0.040000,-0.030000
75%,2007.000000,24.950000,0.320000,26.785000,0.300000,27.597500,0.357500,28.960000,0.250000,0.440000,1.300000,0.800000,0.700000,11.400000,0.740000,0.480000,0.500000,0.530000
max,2026.000000,29.230000,4.470000,29.220000,3.300000,29.420000,2.720000,30.210000,1.540000,4.638000,4.800000,2.900000,2.300000,36.000000,2.660000,2.850000,2.590000,2.400000

In [79]:
prueba.isnull().sum() # Aca me muestra de cada columna suma los valores null

Date                      0
Year                      0
Month                     0
Nino 1+2 SST              3
Nino 1+2 SST Anomaly      3
Nino 3 SST                3
Nino 3 SST Anomaly        3
Nino 3.4 SST              3
Nino 3.4 SST Anomaly      3
Nino 4 SST                3
Nino 4 SST Anomaly        3
TNI                       4
SOI                      12
SOI estandarizado        12
OLR                     309
OLR anomalia            309
PNA                       0
Season (2-Month)          0
MEI.v2                  348
Season (3-Month)          0
ONI                       1
RONI                      1
Fase ENSO (ONI)           1
Intensidad (ONI)        442
Fase ENSO (RONI)          1
Intensidad (RONI)       441
dtype: int64

# Dataset "INDEC_precipitaciones_2010_2024_colab.xlsx":

In [80]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "INDEC_precipitaciones_2010_2024_colab.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/INDEC_precipitaciones_2010_2024_colab.xlsx

In [81]:
#Cargamos los datos
precipitaciones = pd.read_excel(URL + "INDEC_precipitaciones_2010_2024_colab.xlsx")

In [82]:
# Mostramos las primeras 5 filas del Dataset para inspeccionar la estructura inicial y los nombres de las columnas
precipitaciones.head()

       estacion  anio  mes       fecha  precipitacion_mm
0  Buenos Aires  2010    1  2010-01-01             151.8
1  Buenos Aires  2010    2  2010-02-01             419.4
2  Buenos Aires  2010    3  2010-03-01             102.5
3  Buenos Aires  2010    4  2010-04-01              91.9
4  Buenos Aires  2010    5  2010-05-01             125.3

In [83]:
# Mostramos las últimas 5 filas del dataset:
precipitaciones.tail()

     estacion  anio  mes       fecha  precipitacion_mm
4675   Viedma  2024    8  2024-08-01              35.3
4676   Viedma  2024    9  2024-09-01              21.5
4677   Viedma  2024   10  2024-10-01              31.9
4678   Viedma  2024   11  2024-11-01              15.1
4679   Viedma  2024   12  2024-12-01              57.6

In [84]:
# Obtenemos las dimensiones (cantidad de filas y columnas) del Dataset
print("1. Dimensiones del DataFrame (Filas, Columnas):")
print(precipitaciones.shape)

# Consultamos los tipos de datos asignados a cada columna (.dtypes)
print("\n2. Tipos de datos por columna (.dtypes):")
print(precipitaciones.dtypes)

# Mostramos la calidad de los datos
print("\n3. Información general del DataFrame (.info()):")
precipitaciones.info()

# Verificamos la presencia de valores nulos o faltantes por columna sumándolos
print("1. Conteo de valores nulos por columna (.isnull().sum()):")
print(precipitaciones.isnull().sum())

# Verificamos si existen filas duplicadas
print("\n2. Conteo de filas duplicadas:")
print(precipitaciones.duplicated().sum())

# Generamos un resumen estadístico de las variables numéricas (media, desvío, mínimos, cuartiles, máximos)
print("\n3. Estadísticas descriptivas de las variables numéricas (.describe()):")
display(precipitaciones.describe())

1. Dimensiones del DataFrame (Filas, Columnas):
(4680, 5)

2. Tipos de datos por columna (.dtypes):
estacion             object
anio                  int64
mes                   int64
fecha                object
precipitacion_mm    float64
dtype: object

3. Información general del DataFrame (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4680 entries, 0 to 4679
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   estacion          4680 non-null   object
 1   anio              4680 non-null   int64
 2   mes               4680 non-null   int64
 3   fecha             4680 non-null   object
 4   precipitacion_mm  4680 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 182.9+ KB
1. Conteo de valores nulos por columna (.isnull().sum()):
estacion            0
anio                0
mes                 0
fecha               0
precipitacion_mm    0
dtype: int64

2. Conteo de filas duplicadas:
0

3. Estadísticas descriptivas de las variables numéricas (.describe()):

              anio          mes  precipitacion_mm
count  4680.000000  4680.000000       4680.000000
mean   2017.000000     6.500000         64.453889
std       4.320955     3.452421         74.642645
min    2010.000000     1.000000          0.000000
25%    2013.000000     3.750000          9.300000
50%    2017.000000     6.500000         37.800000
75%    2021.000000     9.250000         94.725000
max    2024.000000    12.000000        554.800000

Algunos hallazgos que detectamos en esta exploración inicial:

El DataFrame posee 4.680 registros y 5 columnas (estacion, año, mes, fecha, precipitacion_mm), abarcando 26 estaciones meteorológicas entre los años 2010 y 2024.

El dataset se encuentra completo y consistente; no se encontraron valores nulos ni filas duplicadas.

La precipitación media mensual es de 64.45 mm, con una desviación estándar alta (74.64 mm), lo que refleja la gran variabilidad climática y estacional entre las distintas estaciones del país (desde regiones muy áridas hasta zonas húmedas).

Se trabajó el dataset con IA, ya que el original arrojaba mucha cantidad de Nan y el tipo de datos como object. Debido a esto se le pidió a la IA que ajuste el dataset a una forma que no rompa la estructura y pueda ser trabajado con Python.
El prompt utilizado fue el siguiente: "Armá con este archivo que comparto un Excel que pueda ser leído sin problemas para trabajar con Python desde Colab."

# Dataset "smn_datos_meteorologicos_desde_2021_con_nasa.csv"

In [85]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_datos_meteorologicos_desde_2021_con_nasa.csv")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_datos_meteorologicos_desde_2021_con_nasa.csv

In [86]:
#Cargamos los datos del dataset datos meteorologicos y nasa 2021 y leemos las primeras 5 lineas del principio
import pandas as pd
smn_nasa_2021 = pd.read_csv(URL + "smn_datos_meteorologicos_desde_2021_con_nasa.csv")   # read_csv: leemos el archivo csv
smn_nasa_2021_filtrado = smn_nasa_2021[~smn_nasa_2021['FECHA'].str.contains('2026')].copy() #Filtramos la fecha hasta 2025 debido a que los registros correspondientes a 2026 están en curso y por ende no está completa la información ya que el año no terminó, trabajar con años completos permite evitar sesgos en los análisis y poder dar resultados más claros y concisos
smn_nasa_2021_filtrado.head()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOT,FUENTE
0,87007,LA QUIACA OBSERVATORIO,01/01/2021,24,8.2,15.5,NaN,11.9,9,15,5,671.9,60,2,SMN
1,87007,LA QUIACA OBSERVATORIO,02/01/2021,22,9.2,14.5,2,7.6,23,33,6,671.6,64,4,SMN
2,87007,LA QUIACA OBSERVATORIO,03/01/2021,24.8,7.5,14.5,6,10.9,5,24,8,668.9,64,3,SMN
3,87007,LA QUIACA OBSERVATORIO,04/01/2021,17,5.2,10.7,5,6.6,5,15,5,667.7,74,5,SMN
4,87007,LA QUIACA OBSERVATORIO,05/01/2021,16.7,5,9.5,2,6.7,23,15,6,669.4,74,7,SMN

In [87]:
# Leemos las últimas 5 lineas del dataset:
smn_nasa_2021_filtrado.tail()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOT,FUENTE
183437,87938,USHUAIA AERO,27/12/2025,7.9,1.9,4.2,0.4,S/D,23,80,40,983.4,80,8,SMN
183438,87938,USHUAIA AERO,28/12/2025,7.4,3.2,5.5,6,S/D,36,41,10,994.5,89,8,SMN
183439,87938,USHUAIA AERO,29/12/2025,16.9,6.3,11.3,1,S/D,23,28,12,987.3,83,6,SMN
183440,87938,USHUAIA AERO,30/12/2025,13.5,6.3,9.7,0,S/D,23,106,21,983.9,80,7,SMN
183441,87938,USHUAIA AERO,31/12/2025,9.9,5.6,8.3,2,S/D,23,61,36,996.7,75,6,SMN

In [88]:
#Describimos la estructura del Dataset:
#------------------------------------------------------

#1 - Dimensiones del Conjunto de Datos

# Consultamos las dimensiones del conjunto de datos.
# shape devuelve la cantidad de filas y columnas.

print(f"Dimensiones: {smn_nasa_2021_filtrado.shape}")

# Mostramos por separado la cantidad de registros y variables.
print(f"\nCantidad de filas: {smn_nasa_2021_filtrado.shape[0]}")
print(f"\nCantidad de columnas: {smn_nasa_2021_filtrado.shape[1]}")
print('')

#2 - Tipos de datos

# Consultamos el tipo de dato de cada columna.
# Esto permite distinguir variables numéricas, textos y fechas.

print(smn_nasa_2021_filtrado.dtypes)
print('')


# Obtenemos información general de la tabla: tipo de dato y cantidad de valores no nulos de cada columna.

print(smn_nasa_2021_filtrado.info())
print('')

#Examinando la calidad de los datos del Dataset:
#------------------------------------------------------


#3 - Valores faltantes

# Contamos los valores faltantes en cada columna.

print(smn_nasa_2021_filtrado.isnull().sum())
print('')

#4 - Valores duplicados

# Contamos cuántas filas están completamente duplicadas.

print(f"\nFilas duplicadas: {smn_nasa_2021_filtrado.duplicated().sum()}")
print('')

Dimensiones: (163695, 15)

Cantidad de filas: 163695

Cantidad de columnas: 15

NRO_OMM      int64
NOMBRE      object
FECHA       object
TMAX        object
TMIN        object
TMEDIA      object
PRECIP      object
HELIOF      object
VTO_MDIR    object
VTO_MVEL    object
VEL_MED     object
PRE_EST     object
HUM_REL     object
NUB_TOT     object
FUENTE      object
dtype: object

<class 'pandas.core.frame.DataFrame'>
Index: 163695 entries, 0 to 183441
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   NRO_OMM   163695 non-null  int64
 1   NOMBRE    163695 non-null  object
 2   FECHA     163695 non-null  object
 3   TMAX      163695 non-null  object
 4   TMIN      163695 non-null  object
 5   TMEDIA    163046 non-null  object
 6   PRECIP    44277 non-null   object
 7   HELIOF    163695 non-null  object
 8   VTO_MDIR  163695 non-null  object
 9   VTO_MVEL  163695 non-null  object
 10  VEL_MED   163046 non-null  object
 11  PRE_EST   163046 non-null  object
 12  HUM_REL   163046 non-null  object
 13  NUB_TOT   163046 non-null  object
 14  FUENTE    163695 non-null  object
dtypes: int64(1), object(14)
memory usage: 20.0+ MB
None

NRO_OMM          0
NOMBRE           0
FECHA            0
TMAX             0
TMIN             0
TMEDIA         649
PRECIP      119418
HELIOF           0
VTO_MDIR         0
VTO_MVEL         0
VEL_MED        649
PRE_EST        649
HUM_REL        649
NUB_TOT        649
FUENTE           0
dtype: int64


Filas duplicadas: 0

El dataset cuenta con una estructura definida por 163695 filas y 15 columnas. Este volumen de datos abarca el período de estudio recortado hasta el año 2025, proporcionando la informacion para el análisis meteorológico

Al inspeccionar las columnas, se observa que gran parte de las variables meteorológicas (como temperaturas máximas, mínimas, precipitaciones, entre otras) figuran inicialmente con el tipo de dato object, en lugar de numérico. Esto ocurre de forma frecuente en los registros del Servicio Meteorológico Nacional debido a la presencia de celdas vacías, guiones o códigos de ausencia de datos (como 'S/D'). Este comportamiento anticipa la necesidad de realizar una limpieza y conversión previa antes de calcular promedios o gráficos
El conteo de valores nulos arrojó que varias columnas presentan baches de información. En particular, variables como las precipitaciones o algunas mediciones secundarias concentran una cantidad importante de celdas vacías, lo cual es un comportamiento lógico en estaciones meteorológicas debido a fallas temporales de sensores o registros no tomados

La verificación de filas duplicadas dio como resultado 0. Esto confirma que el archivo filtrado mantiene su consistencia estructural y que no existen filas repetidas que puedan falsear los futuros cálculos estadísticos

In [89]:
# Seleccionamos las columnas que contienen las variables
# Excluimos el texto y la fecha.

variables_meteo = smn_nasa_2021_filtrado.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Revisamos los valores que no pueden interpretarse como números.
# errors="coerce" convierte temporalmente esos valores en NaN.
# No modificamos los datos originales.

for columna in variables_meteo:
    valores = pd.to_numeric(smn_nasa_2021_filtrado[columna], errors="coerce")

    # Contamos los valores no nulos originales que no son numéricos.
    no_numericos = (
        valores.isna() & smn_nasa_2021_filtrado[columna].notna()
    ).sum()

    print(columna, ":", no_numericos, "valores no numéricos")

TMAX : 7101 valores no numéricos
TMIN : 1731 valores no numéricos
TMEDIA : 955 valores no numéricos
PRECIP : 401 valores no numéricos
HELIOF : 42540 valores no numéricos
VTO_MDIR : 4050 valores no numéricos
VTO_MVEL : 4019 valores no numéricos
VEL_MED : 958 valores no numéricos
PRE_EST : 1091 valores no numéricos
HUM_REL : 1030 valores no numéricos
NUB_TOT : 953 valores no numéricos
FUENTE : 163695 valores no numéricos

El conteo nos confirmó que las columnas tienen textos que no pueden ser interpretados como numeros

 Algunas columnas tienen más datos de este tipo que otras. Por ejemplo, las temperaturas son bastante prolijas, pero otras mediciones concentran más registros textuales o faltantes

Esto justifica exactamente por qué usamos errors='coerce'. Gracias a eso pudimos pasar esos textos molestos a valores nulos (NaN)

In [90]:
# Seleccionamos las columnas meteorológicas.

variables_meteo = smn_nasa_2021_filtrado.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Recorremos las variables para conocer cuántos registros son convertibles a números, no convertibles o nulos.

for columna in variables_meteo:

    convertida = pd.to_numeric(
        smn_nasa_2021_filtrado[columna],
        errors="coerce"
    )

    numericos = convertida.notna().sum()

    no_numericos = (
        convertida.isna() & smn_nasa_2021_filtrado[columna].notna()
    ).sum()

    nulos = smn_nasa_2021_filtrado[columna].isna().sum()

    print(
        columna,
        "| Numéricos:", numericos,
        "| No numéricos:", no_numericos,
        "| Nulos:", nulos
    )

TMAX | Numéricos: 156594 | No numéricos: 7101 | Nulos: 0
TMIN | Numéricos: 161964 | No numéricos: 1731 | Nulos: 0
TMEDIA | Numéricos: 162091 | No numéricos: 955 | Nulos: 649
PRECIP | Numéricos: 43876 | No numéricos: 401 | Nulos: 119418
HELIOF | Numéricos: 121155 | No numéricos: 42540 | Nulos: 0
VTO_MDIR | Numéricos: 159645 | No numéricos: 4050 | Nulos: 0
VTO_MVEL | Numéricos: 159676 | No numéricos: 4019 | Nulos: 0
VEL_MED | Numéricos: 162088 | No numéricos: 958 | Nulos: 649
PRE_EST | Numéricos: 161955 | No numéricos: 1091 | Nulos: 649
HUM_REL | Numéricos: 162016 | No numéricos: 1030 | Nulos: 649
NUB_TOT | Numéricos: 162093 | No numéricos: 953 | Nulos: 649
FUENTE | Numéricos: 0 | No numéricos: 163695 | Nulos: 0


Esto nos mostro cuántos valores numéricos, no numéricos y nulos tiene cada variable meteorológica de nuestro Dataset smn_nasa_2021_filtrado, asegurándonos de no modificar los datos originales

---

## ❓ 3.2 Pregunta de investigación


**Pregunta principal:** ¿Qué relación existe entre las fases del fenómeno El Niño–Oscilación del Sur (ENOS) y la frecuencia y simultaneidad de precipitaciones mensuales excepcionalmente altas en el Litoral argentino durante el período 1991–2025?

A los fines de este trabajo, el Litoral comprende Formosa, Chaco, Misiones, Corrientes, Entre Ríos y Santa Fe.

**Pregunta secundaria:** ¿Existe variación de la asociación entre ENOS y precipitaciones excepcionales según la estación del año y el período analizado?

**Pregunta secundaria aplicada:** ¿La información previa del ENOS permite mejorar la predicción de meses con precipitaciones excepcionales respecto de una referencia climatológica?

---

## 🛠️ 3.3 Transformaciones y resumen estadístico "smn_estaciones_meteorologicas21-26.xlsx"

Una transformación importante es el filtrado de las estaciones meteorológicas para seleccionar sólo las pertenecientes al Litoral Argentino. Esto permitirá filtrar a los datasets con las mediciones meteorológicas desde el año 1991 hasta el 2025.
El dataframe que quedará como resultado se llamará **"estaciones_litoral"**

In [91]:
#Aplicamos el filtrado para dejar las estaciones que nos interesan en un dataframe llamado "estaciones_litoral"
#Pero antes voy a aplicar un groupby por nombre de Provincia por si hay algun dato mal cargado en dicho campo:

por_provincia = estaciones.groupby("PROVINCIA")["NRO_OMM"].count().reset_index()
nombre_provincias = por_provincia[["PROVINCIA"]]

print("Filas duplicadas:", nombre_provincias.duplicated().sum())
if nombre_provincias.duplicated().sum() == 0:
  print('No hay duplicados!')
else:
  print('Hay filas duplicadas, vamos a revisar un poco más y eliminarlas')
#display(nombre_provincias)

#Me aseguré que no tengo nombres mal escritos ni duplicados en el campo Provincias
#Ahora aplico el filtro para seleccionar solo las del Litoral
estaciones_litoral = estaciones[(estaciones["PROVINCIA"] == "CORRIENTES") |
                                (estaciones["PROVINCIA"] == "CHACO") |
                                (estaciones["PROVINCIA"] == "ENTRE RÍOS") |
                                (estaciones["PROVINCIA"] == "FORMOSA") |
                                (estaciones["PROVINCIA"] == "MISIONES") |
                                (estaciones["PROVINCIA"] == "SANTA FE") ]
display(estaciones_litoral)

Filas duplicadas: 0
No hay duplicados!

,NRO_OMM,NOMBRE,PROVINCIA,LATITUD,LONGITUD,ALTURA
23,87148,PRESIDENCIA ROQUE SAENZ PEÑA AERO,CHACO,-26.74637,-60.48678,93
24,87155,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52
38,87166,CORRIENTES AERO,CORRIENTES,-27.44979,-58.75974,62
39,87289,PASO DE LOS LIBRES AERO,CORRIENTES,-29.68931,-57.14849,70
40,87393,MONTE CASEROS AERO,CORRIENTES,-30.26172,-57.63900,54
41,87374,PARANÁ AERO,ENTRE RÍOS,-31.79033,-60.48411,78
42,87395,CONCORDIA AERO,ENTRE RÍOS,-31.30223,-58.00147,37
43,87497,GUALEGUAYCHÚ AERO,ENTRE RÍOS,-33.01245,-58.61076,23
44,87078,LAS LOMITAS,FORMOSA,-24.70245,-60.59411,130
45,87162,FORMOSA AERO,FORMOSA,-26.21242,-58.22929,60
59,87097,IGUAZÚ AERO,MISIONES,-25.73108,-54.47897,270
60,87163,BERNARDO DE IRIGOYEN AERO,MISIONES,-26.27793,-53.67121,815
61,87178,POSADAS AERO,MISIONES,-27.39100,-55.96705,125
62,87187,OBERÁ,MISIONES,-27.48372,-55.13158,303
82,87257,CERES AERO,SANTA FE,-29.87556,-61.93604,88
83,87270,RECONQUISTA AERO,SANTA FE,-29.20508,-59.69338,53
84,87371,SAUCE VIEJO AERO,SANTA FE,-31.70780,-60.80532,18
85,87468,VENADO TUERTO,SANTA FE,-33.68226,-61.96136,112
86,87480,ROSARIO AERO,SANTA FE,-32.90816,-60.78216,25
87,87470,EL TRÉBOL,SANTA FE,-32.19216,-61.71198,96

El campo **"NRO_OMM"** será el campo de intersección para los dataframes con las mediciones meteorológicas.

Comenzamos preparando las bases SMN para poder hacer un concat de ambas

Se utilizó IA para trabjar el desarrollo del código para la preparación de las bases previo a concat

PROMPT: A partir de los resultados de los análisis de los datasets que hemos realizado, detecamos que existen algunas diferencias que deben ser trabajadas previo a realizar un concat de ambos. Existe una columna extra en uno de ellos, hay cariables que están asignadas con diferentes tipos (datatype) y columnas con diferente nombres. A partir de los datasets compartidos, vamos a trabajar en el código necesario para poder unir las bases.

1 - Preparación de las bases (SMN 1991 a 2020 y SMN 2021 a 2025)

In [92]:
# Armamos copias para mantener los originales. Trabamos con el smn 2021-2025 filtrado que es el que abarca el período que nos interesa
smn_1991_2020_copia = smn_1991_2020.copy()
smn_2021_2025_copia = smn_nasa_2021_filtrado.copy()

# Unificamos el nombre de la columna de nubosidad
smn_2021_2025_copia = smn_2021_2025_copia.rename(
    columns={"NUB_TOT": "NUB_TOTAL"}
)

# Agregamos la columna FUENTE en el set que faltaba e identificamos el origen de los datos correspondientes al período 1991-2020 (no aparecía en el dataset original)
smn_1991_2020_copia["FUENTE"] = "SMN"

# Función para conservar y clasificar la precipitación original - Esto lo hacemos porque queremos poder discernir entre blancos y S/D (quedarán todos como NaN cuando hagamos la transformación a valor numérico)
def clasificar_precipitacion(df):

    # Conservar el valor original
    df["PRECIP_ORIGINAL"] = df["PRECIP"]

    # Convertir temporalmente a texto para identificar categorías
    texto = df["PRECIP_ORIGINAL"].astype("string").str.strip()

    # Identificar blancos y S/D
    blanco = texto.isna() | texto.eq("").fillna(False)
    sin_dato = texto.str.upper().eq("S/D").fillna(False)

    # Clasificar el estado original
    df["ESTADO_PRECIP"] = np.select(
        [blanco, sin_dato],
        ["Blanco", "S/D"],
        default="Observado"
    )

    return df

# Aplicar la función a ambas bases
smn_1991_2020_copia = clasificar_precipitacion(smn_1991_2020_copia)
smn_2021_2025_copia = clasificar_precipitacion(smn_2021_2025_copia)

# Función para reordenar las columnas para ubicar las nuevas junto a PRECIP

def reordenar_columnas(df):

    columnas = df.columns.tolist()

    # Quitar las columnas que queremos reubicar
    columnas.remove("PRECIP_ORIGINAL")
    columnas.remove("ESTADO_PRECIP")

    # Buscar la posición de PRECIP
    posicion = columnas.index("PRECIP") + 1

    # Insertar las dos columnas después de PRECIP
    columnas[posicion:posicion] = [
        "PRECIP_ORIGINAL",
        "ESTADO_PRECIP"
    ]

    return df[columnas]


# Aplicar la función a ambas bases
smn_1991_2020_copia = reordenar_columnas(smn_1991_2020_copia)
smn_2021_2025_copia = reordenar_columnas(smn_2021_2025_copia)


# Verificamos las columnas
print("Columnas período 1991-2020:")
print(smn_1991_2020_copia.columns.tolist())

print("\nColumnas del período 2021-2026:")
print(smn_2021_2025_copia.columns.tolist())

# Comprobamos que ambas bases tengan las mismas columnas
assert set(smn_1991_2020_copia.columns) == set(smn_2021_2025_copia.columns), (
    "Las bases tienen columnas diferentes. Revisar antes de concatenar."
)

# Ordenamos las columnas de ambas bases de la misma manera
smn_2021_2025_copia = smn_2021_2025_copia[smn_1991_2020_copia.columns]

Columnas período 1991-2020:
['NRO_OMM', 'NOMBRE', 'FECHA', 'TMAX', 'TMIN', 'TMEDIA', 'PRECIP', 'PRECIP_ORIGINAL', 'ESTADO_PRECIP', 'HELIOF', 'VTO_MDIR', 'VTO_MVEL', 'VEL_MED', 'PRE_EST', 'HUM_REL', 'NUB_TOTAL', 'FUENTE']

Columnas del período 2021-2026:
['NRO_OMM', 'NOMBRE', 'FECHA', 'TMAX', 'TMIN', 'TMEDIA', 'PRECIP', 'PRECIP_ORIGINAL', 'ESTADO_PRECIP', 'HELIOF', 'VTO_MDIR', 'VTO_MVEL', 'VEL_MED', 'PRE_EST', 'HUM_REL', 'NUB_TOTAL', 'FUENTE']

In [93]:
smn_1991_2020_copia.head(10)

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,PRECIP_ORIGINAL,ESTADO_PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL,FUENTE
0,87007,LA QUIACA OBSERVATORIO,1991-01-01,18.4,5.4,13.3,5.2,5.2,Observado,S/D,5,9,6,671.4,64,7,SMN
1,87007,LA QUIACA OBSERVATORIO,1991-01-02,18.2,8.4,12.3,8,8,Observado,S/D,32,15,8,670.7,73,7,SMN
2,87007,LA QUIACA OBSERVATORIO,1991-01-03,19.4,6,13.7,NaN,NaN,Blanco,S/D,5,9,4,672,61,4,SMN
3,87007,LA QUIACA OBSERVATORIO,1991-01-04,19.3,4.9,13.1,NaN,NaN,Blanco,S/D,7,15,2,673.2,55,4,SMN
4,87007,LA QUIACA OBSERVATORIO,1991-01-05,21,6,14.2,NaN,NaN,Blanco,S/D,5,15,6,673.4,60,4,SMN
5,87007,LA QUIACA OBSERVATORIO,1991-01-06,21.2,9.4,14,29.4,29.4,Observado,S/D,27,15,9,673.8,64,7,SMN
6,87007,LA QUIACA OBSERVATORIO,1991-01-07,19.3,6.5,12.8,25.5,25.5,Observado,S/D,5,15,1,673.7,68,7,SMN
7,87007,LA QUIACA OBSERVATORIO,1991-01-08,17,8.8,13.2,6,6,Observado,S/D,5,15,10,674.4,74,7,SMN
8,87007,LA QUIACA OBSERVATORIO,1991-01-09,19.2,7.1,13.1,3,3,Observado,S/D,9,15,6,674.5,75,7,SMN
9,87007,LA QUIACA OBSERVATORIO,1991-01-10,16.1,8.5,12.4,16.6,16.6,Observado,S/D,23,15,4,673.3,81,8,SMN

In [94]:
smn_2021_2025_copia.head(10)

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,PRECIP_ORIGINAL,ESTADO_PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL,FUENTE
0,87007,LA QUIACA OBSERVATORIO,01/01/2021,24,8.2,15.5,NaN,NaN,Blanco,11.9,9,15,5,671.9,60,2,SMN
1,87007,LA QUIACA OBSERVATORIO,02/01/2021,22,9.2,14.5,2,2,Observado,7.6,23,33,6,671.6,64,4,SMN
2,87007,LA QUIACA OBSERVATORIO,03/01/2021,24.8,7.5,14.5,6,6,Observado,10.9,5,24,8,668.9,64,3,SMN
3,87007,LA QUIACA OBSERVATORIO,04/01/2021,17,5.2,10.7,5,5,Observado,6.6,5,15,5,667.7,74,5,SMN
4,87007,LA QUIACA OBSERVATORIO,05/01/2021,16.7,5,9.5,2,2,Observado,6.7,23,15,6,669.4,74,7,SMN
5,87007,LA QUIACA OBSERVATORIO,06/01/2021,18.5,5.2,11.1,12,12,Observado,9.6,5,15,5,669.4,75,7,SMN
6,87007,LA QUIACA OBSERVATORIO,07/01/2021,18.5,6.4,11.6,4,4,Observado,0,5,15,6,669.7,70,6,SMN
7,87007,LA QUIACA OBSERVATORIO,08/01/2021,20.5,7.6,12.6,11,11,Observado,9.9,14,15,6,669.6,74,4,SMN
8,87007,LA QUIACA OBSERVATORIO,09/01/2021,21.7,5.1,12.4,NaN,NaN,Blanco,10.9,5,15,6,669.4,65,5,SMN
9,87007,LA QUIACA OBSERVATORIO,10/01/2021,23.4,9.9,15.2,NaN,NaN,Blanco,10,5,15,6,669,62,5,SMN

2 - Estandarizamos los tipos de datos

Es importante que las variables meteorológicas, NRO_OMM y FECHA tengan el tipo compatible. Además, convertimos los S/D y blancos en NaN. Por esto en el paso anterior tuvimos en cuenta de mantener los registros para la trazabilidad

In [95]:
# 1. Comenzamos con las fechas en el dataset 2021-2025

smn_2021_2025_copia["FECHA"] = pd.to_datetime(
    smn_2021_2025_copia["FECHA"],
    errors="coerce",
    dayfirst=True
)


# 2. Definir las variables meteorológicas numéricas
variables_numericas = [
    "TMAX",
    "TMIN",
    "TMEDIA",
    "PRECIP",
    "HELIOF",
    "VTO_MDIR",
    "VTO_MVEL",
    "VEL_MED",
    "PRE_EST",
    "HUM_REL",
    "NUB_TOTAL"
]


# 3. Estandarizar ambas bases
for df in [smn_1991_2020_copia, smn_2021_2025_copia]:

    # Convertir el código de estación a entero
    df["NRO_OMM"] = pd.to_numeric(
        df["NRO_OMM"],
        errors="coerce"
    ).astype("Int64")

    # Limpiar los nombres de las estaciones
    df["NOMBRE"] = (
        df["NOMBRE"]
        .astype("string")
        .str.strip()
    )

    # Convertir las variables meteorológicas a numéricas
    for columna in variables_numericas:

        df[columna] = pd.to_numeric(
            df[columna],
            errors="coerce"
        )

    # Identificar otros valores no numéricos en precipitación
    df.loc[
        df["PRECIP"].isna()
        & (df["ESTADO_PRECIP"] == "Observado"),
        "ESTADO_PRECIP"
    ] = "Otro no numérico"


# 4. Verificar los tipos de datos
print("TIPOS DE DATOS - 1991 a 2020")
print(smn_1991_2020_copia.dtypes)

print("\nTIPOS DE DATOS - 2021 a 2025")
print(smn_2021_2025_copia.dtypes)


# 5. Verificar los estados de precipitación
print("\nESTADO DE PRECIPITACIÓN - 1991 a 2020")
print(smn_1991_2020_copia["ESTADO_PRECIP"].value_counts(dropna=False))

print("\nESTADO DE PRECIPITACIÓN - 2021 a 2025")
print(smn_2021_2025_copia["ESTADO_PRECIP"].value_counts(dropna=False))


# 6. Comprobar que blancos y S/D sean NaN en PRECIP
for nombre, df in [
    ("1991 a 2020", smn_1991_2020_copia),
    ("2021 a 2025", smn_2021_2025_copia)
]:

    faltantes = df["ESTADO_PRECIP"].isin(["Blanco", "S/D"])

    assert df.loc[faltantes, "PRECIP"].isna().all(), (
        f"Error en la conversión de precipitación: {nombre}"
    )

print("\nControl correcto: los blancos y S/D se mantienen identificados.")

TIPOS DE DATOS - 1991 a 2020
NRO_OMM                     Int64
NOMBRE             string[python]
FECHA              datetime64[ns]
TMAX                      float64
TMIN                      float64
TMEDIA                    float64
PRECIP                    float64
PRECIP_ORIGINAL            object
ESTADO_PRECIP              object
HELIOF                    float64
VTO_MDIR                  float64
VTO_MVEL                  float64
VEL_MED                   float64
PRE_EST                   float64
HUM_REL                   float64
NUB_TOTAL                 float64
FUENTE                     object
dtype: object

TIPOS DE DATOS - 2021 a 2025
NRO_OMM                     Int64
NOMBRE             string[python]
FECHA              datetime64[ns]
TMAX                      float64
TMIN                      float64
TMEDIA                    float64
PRECIP                    float64
PRECIP_ORIGINAL            object
ESTADO_PRECIP              object
HELIOF                    float64
VTO_MDIR                  float64
VTO_MVEL                  float64
VEL_MED                   float64
PRE_EST                   float64
HUM_REL                   float64
NUB_TOTAL                 float64
FUENTE                     object
dtype: object

ESTADO DE PRECIPITACIÓN - 1991 a 2020
ESTADO_PRECIP
Blanco       717579
Observado    272361
S/D            2244
Name: count, dtype: int64

ESTADO DE PRECIPITACIÓN - 2021 a 2025
ESTADO_PRECIP
Blanco       119418
Observado     43876
S/D             401
Name: count, dtype: int64

Control correcto: los blancos y S/D se mantienen identificados.

3 - Juntamos ambos datasets

Ya estamos en condiciones de juntar (concatenar) ambos datasets de SMN

In [96]:
# Unir los registros de ambos períodos
smn_unificado_1991_2025 = pd.concat(
    [smn_1991_2020_copia, smn_2021_2025_copia],
    ignore_index=True
)

# Comprobar que no se perdieron registros
assert len(smn_unificado_1991_2025) == len(smn_1991_2020_copia) + len(smn_2021_2025_copia)

# Verificar dimensiones
print("Registros 1991-2020:", len(smn_1991_2020_copia))
print("\nRegistros 2021-2025:", len(smn_2021_2025_copia))
print("\nTotal de registros:", len(smn_unificado_1991_2025))

# Visualizar la base unificada
print("\nAsí se ve el dataset del SMN correspondiente al perído 1991 a 2025")
print()
display(smn_unificado_1991_2025.head(10))

Registros 1991-2020: 992184

Registros 2021-2025: 163695

Total de registros: 1155879

Así se ve el dataset del SMN correspondiente al perído 1991 a 2025

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,PRECIP_ORIGINAL,ESTADO_PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL,FUENTE
0,87007,LA QUIACA OBSERVATORIO,1991-01-01,18.4,5.4,13.3,5.2,5.2,Observado,NaN,5.0,9.0,6.0,671.4,64.0,7.0,SMN
1,87007,LA QUIACA OBSERVATORIO,1991-01-02,18.2,8.4,12.3,8.0,8,Observado,NaN,32.0,15.0,8.0,670.7,73.0,7.0,SMN
2,87007,LA QUIACA OBSERVATORIO,1991-01-03,19.4,6.0,13.7,NaN,NaN,Blanco,NaN,5.0,9.0,4.0,672.0,61.0,4.0,SMN
3,87007,LA QUIACA OBSERVATORIO,1991-01-04,19.3,4.9,13.1,NaN,NaN,Blanco,NaN,7.0,15.0,2.0,673.2,55.0,4.0,SMN
4,87007,LA QUIACA OBSERVATORIO,1991-01-05,21.0,6.0,14.2,NaN,NaN,Blanco,NaN,5.0,15.0,6.0,673.4,60.0,4.0,SMN
5,87007,LA QUIACA OBSERVATORIO,1991-01-06,21.2,9.4,14.0,29.4,29.4,Observado,NaN,27.0,15.0,9.0,673.8,64.0,7.0,SMN
6,87007,LA QUIACA OBSERVATORIO,1991-01-07,19.3,6.5,12.8,25.5,25.5,Observado,NaN,5.0,15.0,1.0,673.7,68.0,7.0,SMN
7,87007,LA QUIACA OBSERVATORIO,1991-01-08,17.0,8.8,13.2,6.0,6,Observado,NaN,5.0,15.0,10.0,674.4,74.0,7.0,SMN
8,87007,LA QUIACA OBSERVATORIO,1991-01-09,19.2,7.1,13.1,3.0,3,Observado,NaN,9.0,15.0,6.0,674.5,75.0,7.0,SMN
9,87007,LA QUIACA OBSERVATORIO,1991-01-10,16.1,8.5,12.4,16.6,16.6,Observado,NaN,23.0,15.0,4.0,673.3,81.0,8.0,SMN

🛠️ **3.3 Transformaciones y resumen estadístico "INDEC_precipitaciones_2010_2024_colab.xlsx"**

Pasamos la columna de formato object (texto) a datetime.

En la exploración inicial vimos que fecha era un objeto. Convertirla a tipo fecha permite ordenar cronológicamente de forma correcta, filtrar por rangos temporales específicos y facilita futuras visualizaciones de series temporales.

In [97]:
# Conversión de tipo de datos: pasamos 'fecha' a datetime
precipitaciones['fecha'] = pd.to_datetime(precipitaciones['fecha'])

Como nuestro enfoque está en el Litoral argentino (comprendiendo las provincias de Formosa, Chaco, Misiones, Corrientes, Entre Ríos y Santa Fe), necesitamos realizar un filtrado geográfico riguroso de las estaciones meteorológicas que pertenecen a estas provincias antes de continuar con las transformaciones.

En el dataset del INDEC, las estaciones meteorológicas ubicadas en esta región son:

Formosa (Estación Formosa)

Chaco (Estación Resistencia)

Misiones (Estación Posadas)

Corrientes (Estación Corrientes)

Entre Ríos (Estación Paraná)

Santa Fe (Estaciones Rosario y Sauce Viejo)

In [98]:
# FILTRADO GEOGRÁFICO: ESTACIONES DEL LITORAL ARGENTINO (Formosa, Chaco, Misiones, Corrientes, Entre Ríos y Santa Fe)
# Lista exacta de estaciones meteorológicas correspondientes al Litoral según la pregunta de investigación
estaciones_litoral = [
    'Formosa',
    'Resistencia',    # Corresponde a Chaco
    'Posadas',        # Corresponde a Misiones
    'Corrientes',
    'Paraná',         # Corresponde a Entre Ríos
    'Rosario',        # Corresponde a Santa Fe
    'Sauce Viejo'     # Corresponde a Santa Fe
]

# Filtramos nuestro DataFrame principal (precipitaciones) para quedarnos solo con estas estaciones
df_litoral = precipitaciones[precipitaciones['estacion'].isin(estaciones_litoral)].copy()

# Verificamos el resultado del filtrado
print(f"Dimensiones del DataFrame original: {precipitaciones.shape}")
print(f"Dimensiones del DataFrame filtrado para el Litoral: {df_litoral.shape}")
print("\nEstaciones del Litoral presentes en el nuevo DataFrame:")
print(df_litoral['estacion'].unique())

# Mostramos las primeras 10 filas del dataset filtrado
display(df_litoral.head(10))

Dimensiones del DataFrame original: (4680, 5)
Dimensiones del DataFrame filtrado para el Litoral: (1260, 5)

Estaciones del Litoral presentes en el nuevo DataFrame:
['Corrientes' 'Formosa' 'Paraná' 'Posadas' 'Resistencia' 'Rosario'
 'Sauce Viejo']

       estacion  anio  mes      fecha  precipitacion_mm
540  Corrientes  2010    1 2010-01-01             265.3
541  Corrientes  2010    2 2010-02-01             131.0
542  Corrientes  2010    3 2010-03-01             132.6
543  Corrientes  2010    4 2010-04-01              47.8
544  Corrientes  2010    5 2010-05-01             212.1
545  Corrientes  2010    6 2010-06-01               3.0
546  Corrientes  2010    7 2010-07-01             110.0
547  Corrientes  2010    8 2010-08-01              57.0
548  Corrientes  2010    9 2010-09-01              97.8
549  Corrientes  2010   10 2010-10-01              45.8

-Creación de columna derivada: Identificación de eventos excepcionalmente altos.

Definimos un umbral basado en el percentil 85 de la región litoral (o un criterio de 150 mm mensuales) para aislar los meses con precipitaciones excepcionalmente altas vinculadas a eventos ENOS (fase El Niño).

-Filtrado temporal estratégico: Alineación con el periodo de estudio o fases críticas.

Filtramos para concentrar el análisis en los años con mayor disponibilidad de registros completos recientes. Por ejemplo, el periodo 2010-2024 contenido en el dataset del INDEC para evaluar simultaneidad.

In [99]:
# Creamos la columna umbral_excepcional para identificar los eventos excepcionalmente altos
umbral_excepcional = 150.0 # mm mensuales

def clasificar_excepcionalidad(mm):
    if pd.isna(mm):
        return "Sin dato"
    elif mm >= umbral_excepcional:
        return "Precipitación Excepcionalmente Alta (>=150mm)"
    else:
        return "Precipitación Normal/Baja (<150mm)"

df_litoral['categoria_excepcionalidad'] = df_litoral['precipitacion_mm'].apply(clasificar_excepcionalidad)

# Filtramos los años con mayor disponibilidad de registros completos recientes
df_litoral_reciente = df_litoral[df_litoral['anio'] >= 2015].copy()

print(f"Dimensiones del dataset completo: {precipitaciones.shape}")
print(f"Dimensiones del dataset filtrado para el Litoral (2010-2024): {df_litoral.shape}")
print(f"Dimensiones tras el filtro temporal reciente (2015-2024): {df_litoral_reciente.shape}")

# Mostramos las primeras filas con las nuevas transformaciones
display(df_litoral[['estacion', 'anio', 'mes', 'precipitacion_mm', 'categoria_excepcionalidad']].head())

Dimensiones del dataset completo: (4680, 5)
Dimensiones del dataset filtrado para el Litoral (2010-2024): (1260, 6)
Dimensiones tras el filtro temporal reciente (2015-2024): (840, 6)

,estacion,anio,mes,precipitacion_mm,categoria_excepcionalidad
540,Corrientes,2010,1,265.3,Precipitación Excepcionalmente Alta (>=150mm)
541,Corrientes,2010,2,131.0,Precipitación Normal/Baja (<150mm)
542,Corrientes,2010,3,132.6,Precipitación Normal/Baja (<150mm)
543,Corrientes,2010,4,47.8,Precipitación Normal/Baja (<150mm)
544,Corrientes,2010,5,212.1,Precipitación Excepcionalmente Alta (>=150mm)

Justificación de las transformaciones realizadas (Enfoque Litoral / ENOS):


Creación de columna derivada (categoria_excepcionalidad): Se transformó la variable numérica continua en una categoría binaria/cualitativa para detectar precipitaciones mensuales excepcionalmente altas (>=150mm). Esta transformación responde directamente al núcleo de la pregunta de investigación, permitiendo contabilizar la frecuencia y evaluar posteriormente la simultaneidad de eventos extremos en las provincias del Litoral.

Filtrado geográfico y temporal (estaciones_litoral): Se restringió el dataset a las estaciones meteorológicas correspondientes a Formosa, Chaco, Misiones, Corrientes, Entre Ríos y Santa Fe. Esto aísla la señal climática regional característica de la cuenca del Plata, la cual es altamente sensible a las ondas de teleconexión del fenómeno ENOS.

-Estadísticos:

Utilizamos .groupby para agrupar los datos por estación y año, de esta forma calculamos estadísticas descriptivas para detectar mayores
volúmenes y picos extremos de lluvia en el litoral y los años con mayor acumulación hídrica regional.

In [100]:
# Agrupamiento 1: Resumen por Estación del Litoral (Promedio, Máximo y Acumulado)
# Permite comparar qué estaciones del Litoral concentran los mayores volúmenes y picos extremos de lluvia.
resumen_litoral_estacion = df_litoral.groupby('estacion')['precipitacion_mm'].agg(
    Promedio_Mensual_mm='mean',
    Maximo_Historico_mm='max',
    Desvio_Estandar_mm='std',
    Meses_Totales_Registrados='count'
).reset_index().sort_values(by='Promedio_Mensual_mm', ascending=False)

print("--- 1. Resumen estadístico agrupado por Estación en el Litoral ---")
display(resumen_litoral_estacion)


# Agrupamiento 2: Resumen por Año a nivel Regional (Frecuencia de eventos extremos y promedios)
# Agrupamos por año para evaluar la variabilidad interanual y detectar los años con mayor acumulación hídrica regional.
resumen_litoral_anual = df_litoral.groupby('anio')['precipitacion_mm'].agg(
    Promedio_Regional_mm='mean',
    Suma_Total_Regional_mm='sum',
    Maximo_Registrado_Regional_mm='max'
).reset_index()

print("\n--- 2. Resumen estadístico agrupado por Año en el Litoral ---")
display(resumen_litoral_anual)

--- 1. Resumen estadístico agrupado por Estación en el Litoral ---

,estacion,Promedio_Mensual_mm,Maximo_Historico_mm,Desvio_Estandar_mm,Meses_Totales_Registrados
3,Posadas,163.251667,548.2,115.957466,180
4,Resistencia,114.615000,554.8,96.032510,180
1,Formosa,114.051111,473.7,90.179831,180
0,Corrientes,113.396111,518.3,95.777754,180
2,Paraná,91.682222,356.0,74.890222,180
6,Sauce Viejo,89.572222,405.0,75.570246,180
5,Rosario,82.428333,378.3,73.620572,180

--- 2. Resumen estadístico agrupado por Año en el Litoral ---

,anio,Promedio_Regional_mm,Suma_Total_Regional_mm,Maximo_Registrado_Regional_mm
0,2010,103.929762,8730.1,356.0
1,2011,98.660714,8287.5,313.0
2,2012,109.996429,9239.7,416.1
3,2013,102.436905,8604.7,355.2
4,2014,132.809524,11156.0,422.1
5,2015,126.161905,10597.6,465.9
6,2016,126.221429,10602.6,378.3
7,2017,124.627381,10468.7,548.2
8,2018,116.363095,9774.5,405.0
9,2019,128.834524,10822.1,554.8
10,2020,76.288095,6408.2,266.6
11,2021,93.825000,7881.3,291.3
12,2022,80.747619,6782.8,370.2
13,2023,109.153571,9168.9,480.7
14,2024,117.794048,9894.7,446.3

Interpretación de los estadísticos agrupados en relación con la pregunta de investigación:

Análisis por Estación del Litoral (groupby('estacion')): Los estadísticos demuestran un gradiente norte-sur y este-oeste muy marcado en el Litoral. Estaciones como Posadas (Misiones) y Corrientes registran los promedios mensuales y máximos históricos más elevados (superando ampliamente los 300-500mm en un solo mes), lo que indica que el noreste del Litoral es la zona más vulnerable a acumulados extremos. En contraste, estaciones del sur del Litoral (como Paraná, Rosario o Sauce Viejo) presentan medias mensuales moderadas pero con picos estacionales de alta intensidad, claves para estudiar la simultaneidad de desbordes e inundaciones en la cuenca del Paraná.

Análisis por Año en la Región (groupby('anio')): El resumen anual del promedio y la suma total de precipitaciones en el Litoral revela fluctuaciones interanuales acentuadas. Se identifican años con volúmenes regionales excepcionalmente altos que coinciden con años de desarrollo e intensidad de eventos cálidos de El Niño, aportando el sustento empírico inicial para vincular la periodicidad del ENOS con la ocurrencia macro de precipitaciones extraordinarias en las seis provincias que componen el Litoral.

🛠️ **3.3 Transformaciones y resumen estadístico "indices_enso_noaa_pacifico.csv"**

In [101]:

# Convertimos la columna 'Date' (object) a formato de fecha (datetime)
prueba['Date'] = pd.to_datetime(prueba['Date'])
prueba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  921 non-null    datetime64[ns]
 1   Year                  921 non-null    int64
 2   Month                 921 non-null    object
 3   Nino 1+2 SST          918 non-null    float64
 4   Nino 1+2 SST Anomaly  918 non-null    float64
 5   Nino 3 SST            918 non-null    float64
 6   Nino 3 SST Anomaly    918 non-null    float64
 7   Nino 3.4 SST          918 non-null    float64
 8   Nino 3.4 SST Anomaly  918 non-null    float64
 9   Nino 4 SST            918 non-null    float64
 10  Nino 4 SST Anomaly    918 non-null    float64
 11  TNI                   917 non-null    float64
 12  SOI                   909 non-null    float64
 13  SOI estandarizado     909 non-null    float64
 14  OLR                   612 non-null    float64
 15  OLR anomalia          612 non-null    float64
 16  PNA                   921 non-null    float64
 17  Season (2-Month)      921 non-null    object
 18  MEI.v2                573 non-null    float64
 19  Season (3-Month)      921 non-null    object
 20  ONI                   920 non-null    float64
 21  RONI                  920 non-null    float64
 22  Fase ENSO (ONI)       920 non-null    object
 23  Intensidad (ONI)      479 non-null    object
 24  Fase ENSO (RONI)      920 non-null    object
 25  Intensidad (RONI)     480 non-null    object
dtypes: datetime64[ns](1), float64(17), int64(1), object(7)
memory usage: 187.2+ KB

In [102]:

# Reemplazamos los valores nulos en 'Intensidad (ONI)' con la etiqueta 'Neutral'
prueba['Intensidad (ONI)'] = prueba['Intensidad (ONI)'].fillna('Neutral')
prueba.tail()
#Antes en el indice 920 columna "Intensidad (ONI)" decia "Nan", ahora dice "Neutral"

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
916,2026-05-01,2026,MAY,26.23,1.82,28.41,1.16,28.83,0.90,30.00,...,-1.2693,AM,0.27,AMJ,0.95,0.49,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
917,2026-06-01,2026,JUN,25.94,2.82,28.33,1.71,29.17,1.44,30.19,...,-0.5005,MJ,1.52,MJJ,1.39,0.97,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
918,2026-07-01,2026,JUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6149,JJ,2.41,JJA,1.80,1.36,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
919,2026-08-01,2026,AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0797,JA,2.54,JAS,2.16,1.69,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
920,2026-09-01,2026,SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.6415,AS,2.37,ASO,NaN,NaN,NaN,Neutral,NaN,NaN

In [103]:
# Estadístico 1: Promedio de la anomalía de temperatura (Nino 3.4 SST Anomaly) por Fase ENSO
promedio_anomalia = prueba.groupby('Fase ENSO (ONI)')['Nino 3.4 SST Anomaly'].mean()
print("Promedio de Anomalía SST por Fase:")
print(promedio_anomalia)
print("-" * 30)

Promedio de Anomalía SST por Fase:
Fase ENSO (ONI)
El Niño    0.917741
La Niña   -1.160882
Neutral   -0.232812
Name: Nino 3.4 SST Anomaly, dtype: float64
------------------------------

**El Niño: 0.917741: Significa que, durante los meses clasificados como El Niño, el agua estuvo en promedio casi 1°C más caliente de lo normal. Al estar más caliente, se evapora más agua y altera los vientos globales, empujando enormes cantidades de humedad hacia el litoral argentino. Esto es lo que causa las temporadas de lluvias extremas**

**La Niña : -1.160882: Muestra que el agua estuvo, en promedio, 1.16°C más fría de lo habitual. Esta anomalía negativa corta el suministro de humedad hacia el noreste argentino, provocando lo contrario: sequías severas y bajantes históricas en los ríos de la región**

**Neutral: -0.232812: Indica que la temperatura estuvo muy cerca del promedio histórico. En estas condiciones, el clima del litoral no está fuertemente forzado por el océano Pacífico y las lluvias dependen más de factores locales.**

In [104]:
# Valor máximo del índice ONI agrupado por la Intensidad de la fase
maximo_oni_intensidad = prueba.groupby('Intensidad (ONI)')['ONI'].max()
print("Máximo índice ONI por Intensidad:")
print(maximo_oni_intensidad)

Máximo índice ONI por Intensidad:
Intensidad (ONI)
Débil         0.88
Fuerte        1.84
Moderado      1.19
Muy fuerte    2.59
Neutral       0.76
Name: ONI, dtype: float64

# Merge de Registros del SMN unificado y Estaciones del Litoral

In [105]:
import pandas as pd

columna_clave = "NRO_OMM"

# 1. Preparar el dataset unificado del SMN
df_smn = smn_unificado_1991_2025.copy()
df_smn[columna_clave] = df_smn[columna_clave].astype(str).str.strip()

# 2. Preparar el dataset del Litoral
# Como 'estaciones_litoral' es una lista de nombres de estaciones, filtramos el DataFrame 'estaciones' original
nombres_busqueda = [est.lower().strip() for est in estaciones_litoral]
condicion_litoral = estaciones['NOMBRE'].str.lower().apply(lambda x: any(nom in x for nom in nombres_busqueda))
df_litoral = estaciones[condicion_litoral].copy()

df_litoral[columna_clave] = df_litoral[columna_clave].astype(str).str.strip()

# 3. Realizar la combinación (merge) usando la intersección de ambos
df_merged = pd.merge(
    df_smn,
    df_litoral,
    on=columna_clave,
    how='inner',
    suffixes=('_smn', '_litoral')
)

# 4. Verificación de resultados
print(f"Filas en SMN original: {len(df_smn)}")
print(f"Filas resultantes en el Litoral unificado (merge): {len(df_merged)}")

display(df_merged.head())

Filas en SMN original: 1155879
Filas resultantes en el Litoral unificado (merge): 89420

,NRO_OMM,NOMBRE_smn,FECHA,TMAX,TMIN,TMEDIA,PRECIP,PRECIP_ORIGINAL,ESTADO_PRECIP,HELIOF,...,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL,FUENTE,NOMBRE_litoral,PROVINCIA,LATITUD,LONGITUD,ALTURA
0,87155,RESISTENCIA AERO,1991-01-01,32.1,22.4,27.3,26.5,26.5,Observado,1.3,...,13.0,1000.5,69.0,5.0,SMN,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52
1,87155,RESISTENCIA AERO,1991-01-02,28.0,21.6,24.2,4.0,4,Observado,1.0,...,10.0,1001.5,87.0,7.0,SMN,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52
2,87155,RESISTENCIA AERO,1991-01-03,32.1,21.4,26.7,NaN,NaN,Blanco,7.2,...,7.0,1002.1,77.0,4.0,SMN,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52
3,87155,RESISTENCIA AERO,1991-01-04,32.2,22.4,26.8,NaN,NaN,Blanco,8.9,...,13.0,1004.0,66.0,1.0,SMN,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52
4,87155,RESISTENCIA AERO,1991-01-05,33.4,20.4,26.3,NaN,NaN,Blanco,NaN,...,9.0,1003.8,60.0,1.0,SMN,RESISTENCIA AERO,CHACO,-27.43888,-59.04602,52

Definir la clave en común: Usamos la columna NRO_OMM (que es el número oficial de cada estación meteorológica) como el cruce exacto para unir el archivo histórico del SMN (1991-2025) con el de las estaciones del Litoral para luego poder utilizarlo de forma mas ordenada, visualmente facil y limpia para el analisis

Limpiar y normalizar los datos: Antes de unirlos, armamos copias de seguridad de las tablas con .copy() para no romper nada original. Después, con astype(str) y .str.strip(), nos aseguramos de que los códigos de las estaciones queden todos escritos exactamente igual como texto y sin espacios de más, para que el programa no se confunda y los reconozca bien

Hacer el merge: Usamos la función pd.merge() indicándole la clave con on=columna_clave. Le pusimos how='inner' para quedarnos únicamente con la intersección (es decir, los datos del SMN que pertenecen justo a las estaciones del Litoral). También le agregamos suffixes=('_smn', '_litoral') por si las dos tablas tenían columnas con el mismo nombre, logrando así que no se pisen entre sí

Controlar que todo haya salido bien: Por último, con ayuda y recoemndacion de la inteligencia artificial incorporamos comandos como len() para ver cuántas filas quedaron después del filtro y display(head()) para visualizar las primeras filas y comprobar que la tabla nueva se armó como queríamos